jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        cache: gradle
        distribution: temurin
        java-version: 17
    - continue-on-error: true
      if: github.event_name != 'pull_request' && github.ref == 'refs/heads/main'
      name: Write key
      run: 'if [ ! -z "${{ secrets.SIGNING_KEY }}" ]; then

        echo releaseStorePassword=''${{ secrets.KEY_STORE_PASSWORD }}'' >> gradle.properties

        echo releaseKeyAlias=''${{ secrets.ALIAS }}'' >> gradle.properties

        echo releaseKeyPassword=''${{ secrets.KEY_PASSWORD }}'' >> gradle.properties

        echo releaseStoreFile=''key.jks'' >> gradle.properties

        echo ${{ secrets.SIGNING_KEY }} | base64 --decode > key.jks

        fi

        '
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew assembleRelease assembleDebug
    - continue-on-error: true
      name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: Signed app bundle
        path: app/build/outputs/apk
name: Android CI
on:
  repository_dispatch:
    types: trigger-ga___android.yml
